[tool.pytest.ini_options]
markers = [
    "unit: marks tests as unit tests (fast, isolated)",
    "integration: marks tests as integration tests (slower, with dependencies)",
    "slow: marks tests as slow running",
    "smoke: marks tests as smoke tests (basic functionality)",
]